services:
  app:
    build: .
    image: controlparental:latest
    env_file:
      - .env
    volumes:
      - .env:/var/www/.env
      - ./storage:/var/www/storage
      - public-volume:/var/www/public
    networks: [net]
    depends_on: [mysql]

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - public-volume:/var/www/public:ro
    ports:
      - "8080:80"
    depends_on: [app]
    networks: [net]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: controlparental
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks: [net]

networks:
  net:

volumes:
  mysql-data:
  public-volume:
